name: sam3d_gui
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.0.5
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - certifi==2022.12.7
      - cffi==2.0.0
      - charset-normalizer==2.1.1
      - cmake==3.25.0
      - cython==3.2.1
      - dataclasses-json==0.6.7
      - debugpy==1.8.17
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - entrypoints==0.4
      - filelock==3.19.1
      - fqdn==1.5.1
      - gradio==6.0.0
      - gradio-client==2.0.0.dev3
      - idna==3.4
      - importlib-metadata==8.7.0
      - ipycanvas==0.14.1
      - ipyevents==2.0.4
      - ipykernel==7.1.0
      - isoduration==20.11.0
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - kaolin==0.17.0
      - lark==1.3.1
      - lit==15.0.7
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - mistune==3.1.4
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.7.0
      - networkx==3.3
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - open3d==0.17.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pexpect==4.9.0
      - pillow==11.3.0
      - prometheus-client==0.23.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pybind11==3.0.1
      - pycparser==2.23
      - pygltflib==1.16.5
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - send2trash==1.8.3
      - six==1.17.0
      - soupsieve==2.8
      - sympy==1.14.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - torch==2.0.0+cu118
      - torchaudio==2.0.0+cu118
      - torchvision==0.15.0+cu118
      - tornado==6.5.2
      - triton==2.0.0
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - uri-template==1.3.0
      - urllib3==1.26.13
      - usd-core==25.11
      - utils3d==0.1.1
      - warp-lang==1.10.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - wrapt==2.0.1
      - zipp==3.23.0
      # SAM3D 핵심 패키지 (추가)
      - einops==0.8.1
      - einops-exts==0.0.4
      - trimesh==4.9.0
      - opencv-python==4.12.0.88
      - scipy==1.15.3
      - safetensors==0.6.2
      - huggingface-hub==0.36.0
prefix: /home/joon/miniconda3/envs/sam3d_gui
